name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          brew install leiningen
          git submodule init
          git submodule update --init --recursive

          mkdir -p src/java/datalevin/dtlvnative/macosx-arm64
          mkdir -p macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64

          export MACOSX_DEPLOYMENT_TARGET=10.14

          brew install leiningen libomp llvm

          script/build-macos
          cp src/*.dylib macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64/

          cd macosx-arm64
          lein deps

          cd ../src/java
          java -jar ~/.m2/repository/org/bytedeco/javacpp/1.5.11/javacpp-1.5.11.jar datalevin/dtlvnative/DTLV.java

          cd ../..
          cp src/java/datalevin/dtlvnative/macosx-arm64/*.dylib macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64/

          cd macosx-arm64
          lein run
          lein jar
      - uses: actions/upload-artifact@v4
        with:
          name: dtlvnative-macosx-arm64-0.12.8.jar
          path: macosx-arm64/target/dtlvnative-macosx-arm64-0.12.8.jar

